//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Readers.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FaceDetectSoap")]
    public interface FaceDetectSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateDir(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateDirAsync(string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FaceDetectSoapChannel : Readers.ServiceReference1.FaceDetectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaceDetectSoapClient : System.ServiceModel.ClientBase<Readers.ServiceReference1.FaceDetectSoap>, Readers.ServiceReference1.FaceDetectSoap {
        
        public FaceDetectSoapClient() {
        }
        
        public FaceDetectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaceDetectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaceDetectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaceDetectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateDir(string location) {
            return base.Channel.CreateDir(location);
        }
        
        public System.Threading.Tasks.Task<string> CreateDirAsync(string location) {
            return base.Channel.CreateDirAsync(location);
        }
    }
}
